In [17]:
a = 1; print(type(a))

<class 'int'>


## print(type(a))
- "class x" 꼴로 타입을 출력함(단순히 type(x)인 경우는 class가 붙지 않음)

In [18]:
a = 1; a = float(a); print(type(a))

<class 'float'>


- 참고: int(정수), float(소수)

In [19]:
a = 1.2; a = int(a); print(type(a))

<class 'int'>


- 주의: int(a) 하였다고 a 자체가 정수화되는 것은 아님. 그냥 단순히 출력값이 정수화되어 나오는 것.

In [20]:
a = '123'; print(type(a)); print(a[1])

<class 'str'>
2


In [1]:
a = '123'; type(a); a[1]

'2'

## print(a)의 이점
- [20]과 [1] 비교; print(X)의 값은 모조리 도출되나 print가 없는 경우는 맨 마지막 요청값만 도출됨

- str(string). 문자열

In [21]:
a = '123'; a = list(a); print(type(a)); print(a); print(a[2])

<class 'list'>
['1', '2', '3']
3


- a의 값은 최초 string이었음
- 그러나 두번째 수식을 통해 a의 값이 list로 재할당됨
- 문자열의 각 철자가 list의 원소가 되는 방식으로 재할당됨

In [22]:
a = [1,'2', [3, '4']]; print(type(a)); print(a[0]); print(a[1]); print(a[2])

<class 'list'>
1
2
[3, '4']


- list안에 또다른 list 포함가능(recursive)

In [3]:
a = [1,'s', [3, '4']]; print(a[1])

s


- 문자의 경우는 따옴표를 떼고 나온다.
- 그러나 [22]에서 print(a[2])=[3,'4']로 4에 따옴표가 붙여나온 이유는 [3,'4'] 자체를 하나의 원소로 보기 때문.

In [23]:
a = (1,'2', [3, '4']); print(type(a)); print(a[0]); print(a[1]); print(a[2])

<class 'tuple'>
1
2
[3, '4']


## tuple
- 원소들의 집합체
- ( ) 사용
- list는 가변적인 집합체이나 tuple은 변하지 않는 집합체이다(https://robot7887.blog.me/221361350489)
- 추후에 더 많은 코드를 배우면 차이가 명확해질듯 함

In [24]:
a =	{"a": "apple", "b": "orange", "c": 2014}
print(type(a))
print(a["a"])

<class 'dict'>
apple


## dict
- 원소들의 집합체
- { } 사용
- 각 원소에 이름을 붙여줌. 이름은 문자가 될수도 숫자가 될수도.
- print(a["a"]) 의미 = a에서 "a"라는 원소는 무엇이라고 불리는가?

# ----------------------------------list. tuple. dict를 확실히 구분할것.

In [5]:
a=[(1,2,3), (3,8,0)]
print(type(a))
a

<class 'list'>


[(1, 2, 3), (3, 8, 0)]

In [6]:
import numpy as np
b = np.array(a)
print(b)
print(type(b))

[[1 2 3]
 [3 8 0]]
<class 'numpy.ndarray'>


## numpy
- 패키지
- 과학적인 용도로 배열 연산에 강점이 있지만 거기에 한정되지 않고 다차원 데이터의 저장 방법으로 사용될 수 있다(http://engineerk.com/221392020475)
- import numpy as np 수식을 통해 numpy 패키지를 추가함

- array: 함수 -> 행렬화
- ndarray : array 함수로 만든 다차원 배열의 데이터 타입

In [7]:
import numpy
b = numpy.array(a)
print(b)
print(type(b))

[[1 2 3]
 [3 8 0]]
<class 'numpy.ndarray'>


- numpy as np로 안받았으면 그냥 계속 numpy라고 사용하면 됨!

In [29]:
print(b*b)

[[ 1  4  9]
 [ 9 64  0]]


In [30]:
c = np.matrix(b)
print(c)
print(type(c))

[[1 2 3]
 [3 8 0]]
<class 'numpy.matrixlib.defmatrix.matrix'>


- np.matrix() 수식을 통해 행렬의 class가 바뀜. 행렬의 값은 그대로.
- array와 matrix 의 차이는??

In [31]:
c*c

ValueError: shapes (2,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

- array는 행렬의 곱이 가능하나, matrix의 경우는 행렬의 곱이 불가능함(원래 행렬끼리 곱하는 상식대로 처리)

In [32]:
c*c.T

matrix([[14, 19],
        [19, 73]])

- .T -> transfose(flip) : 행렬을 뒤바꿈
- 행렬을 뒤바꾸니까 (2.3) 과 (3.2)과의 곱셈이됨
- 곱셈가능!

In [7]:
s='abcdef'; print(type(s))

<class 'str'>


In [9]:
s='abcdef'
type(s)

str

print(type( 이랑 type() 이랑 구분할것, 결과값이 다름